package com.youku.soku.manage.torque;

/**
 * Permission Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Jan 12 18:40:26 CST 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class AuthPermissionPeer
    extends com.youku.soku.manage.torque.BaseAuthPermissionPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1263292826671L;

}
