package com.youku.soku.manage.torque;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;



            

/**
 * ·´À¡
 *
 * This class was autogenerated by Torque on:
 *
 * [Mon Jun 13 16:33:58 CST 2011]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to SokuFeedbackUnion
 */
public abstract class BaseSokuFeedbackUnion extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1307954038965L;

    /** The Peer class */
    private static final SokuFeedbackUnionPeer peer =
        new SokuFeedbackUnionPeer();

        
    /** The value for the id field */
    private int id;
      
    /** The value for the state field */
    private int state;
      
    /** The value for the source field */
    private int source;
      
    /** The value for the feedbackDate field */
    private Date feedbackDate;
      
    /** The value for the type field */
    private int type;
      
    /** The value for the count field */
    private int count;
  
            
    /**
     * Get the Id
     *
     * @return int
     */
    public int getId()
    {
        return id;
    }

                        
    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(int v) 
    {
    
                  if (this.id != v)
              {
            this.id = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the State
     *
     * @return int
     */
    public int getState()
    {
        return state;
    }

                        
    /**
     * Set the value of State
     *
     * @param v new value
     */
    public void setState(int v) 
    {
    
                  if (this.state != v)
              {
            this.state = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Source
     *
     * @return int
     */
    public int getSource()
    {
        return source;
    }

                        
    /**
     * Set the value of Source
     *
     * @param v new value
     */
    public void setSource(int v) 
    {
    
                  if (this.source != v)
              {
            this.source = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the FeedbackDate
     *
     * @return Date
     */
    public Date getFeedbackDate()
    {
        return feedbackDate;
    }

                        
    /**
     * Set the value of FeedbackDate
     *
     * @param v new value
     */
    public void setFeedbackDate(Date v) 
    {
    
                  if (!ObjectUtils.equals(this.feedbackDate, v))
              {
            this.feedbackDate = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Type
     *
     * @return int
     */
    public int getType()
    {
        return type;
    }

                        
    /**
     * Set the value of Type
     *
     * @param v new value
     */
    public void setType(int v) 
    {
    
                  if (this.type != v)
              {
            this.type = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Count
     *
     * @return int
     */
    public int getCount()
    {
        return count;
    }

                        
    /**
     * Set the value of Count
     *
     * @param v new value
     */
    public void setCount(int v) 
    {
    
                  if (this.count != v)
              {
            this.count = v;
            setModified(true);
        }
    
          
              }
  
         
                
    private static List<String> fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List<String> getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList<String>();
              fieldNames.add("Id");
              fieldNames.add("State");
              fieldNames.add("Source");
              fieldNames.add("FeedbackDate");
              fieldNames.add("Type");
              fieldNames.add("Count");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("Id"))
        {
                return new Integer(getId());
            }
          if (name.equals("State"))
        {
                return new Integer(getState());
            }
          if (name.equals("Source"))
        {
                return new Integer(getSource());
            }
          if (name.equals("FeedbackDate"))
        {
                return getFeedbackDate();
            }
          if (name.equals("Type"))
        {
                return new Integer(getType());
            }
          if (name.equals("Count"))
        {
                return new Integer(getCount());
            }
          return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occures with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
          if (name.equals("Id"))
        {
                      if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setId(((Integer) value).intValue());
                      return true;
        }
          if (name.equals("State"))
        {
                      if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setState(((Integer) value).intValue());
                      return true;
        }
          if (name.equals("Source"))
        {
                      if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setSource(((Integer) value).intValue());
                      return true;
        }
          if (name.equals("FeedbackDate"))
        {
                      // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setFeedbackDate((Date) value);
                      return true;
        }
          if (name.equals("Type"))
        {
                      if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setType(((Integer) value).intValue());
                      return true;
        }
          if (name.equals("Count"))
        {
                      if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setCount(((Integer) value).intValue());
                      return true;
        }
          return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(SokuFeedbackUnionPeer.ID))
        {
                return new Integer(getId());
            }
          if (name.equals(SokuFeedbackUnionPeer.STATE))
        {
                return new Integer(getState());
            }
          if (name.equals(SokuFeedbackUnionPeer.SOURCE))
        {
                return new Integer(getSource());
            }
          if (name.equals(SokuFeedbackUnionPeer.FEEDBACK_DATE))
        {
                return getFeedbackDate();
            }
          if (name.equals(SokuFeedbackUnionPeer.TYPE))
        {
                return new Integer(getType());
            }
          if (name.equals(SokuFeedbackUnionPeer.COUNT))
        {
                return new Integer(getCount());
            }
          return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occures with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (SokuFeedbackUnionPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
        if (SokuFeedbackUnionPeer.STATE.equals(name))
        {
            return setByName("State", value);
        }
        if (SokuFeedbackUnionPeer.SOURCE.equals(name))
        {
            return setByName("Source", value);
        }
        if (SokuFeedbackUnionPeer.FEEDBACK_DATE.equals(name))
        {
            return setByName("FeedbackDate", value);
        }
        if (SokuFeedbackUnionPeer.TYPE.equals(name))
        {
            return setByName("Type", value);
        }
        if (SokuFeedbackUnionPeer.COUNT.equals(name))
        {
            return setByName("Count", value);
        }
          return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getId());
            }
              if (pos == 1)
        {
                return new Integer(getState());
            }
              if (pos == 2)
        {
                return new Integer(getSource());
            }
              if (pos == 3)
        {
                return getFeedbackDate();
            }
              if (pos == 4)
        {
                return new Integer(getType());
            }
              if (pos == 5)
        {
                return new Integer(getCount());
            }
              return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occures with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (position == 0)
        {
            return setByName("Id", value);
        }
          if (position == 1)
        {
            return setByName("State", value);
        }
          if (position == 2)
        {
            return setByName("Source", value);
        }
          if (position == 3)
        {
            return setByName("FeedbackDate", value);
        }
          if (position == 4)
        {
            return setByName("Type", value);
        }
          if (position == 5)
        {
            return setByName("Count", value);
        }
              return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(SokuFeedbackUnionPeer.DATABASE_NAME);
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    SokuFeedbackUnionPeer.doInsert((SokuFeedbackUnion) this, con);
                    setNew(false);
                }
                else
                {
                    SokuFeedbackUnionPeer.doUpdate((SokuFeedbackUnion) this, con);
                }
                }

                      alreadyInSave = false;
        }
      }

                  
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
            setId(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
            setId(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getId());
      }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public SokuFeedbackUnion copy() throws TorqueException
    {
            return copy(true);
        }
  
          /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public SokuFeedbackUnion copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new SokuFeedbackUnion(), deepcopy);
    }
      
      /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     * @param copyObj the object to fill.
     */
    protected SokuFeedbackUnion copyInto(SokuFeedbackUnion copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }
      
    /**
     * Fills the copyObj with the contents of this object.
       * If deepcopy is true, The associated objects are also copied 
     * and treated as new objects.
       * @param copyObj the object to fill.
       * @param deepcopy whether the associated objects should be copied.
       */
      protected SokuFeedbackUnion copyInto(SokuFeedbackUnion copyObj, boolean deepcopy) throws TorqueException
      {
          copyObj.setId(id);
          copyObj.setState(state);
          copyObj.setSource(source);
          copyObj.setFeedbackDate(feedbackDate);
          copyObj.setType(type);
          copyObj.setCount(count);
  
                            copyObj.setId( 0);
                                          
          if (deepcopy) 
        {
            }
          return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public SokuFeedbackUnionPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return SokuFeedbackUnionPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("SokuFeedbackUnion:\n");
        str.append("Id = ")
               .append(getId())
             .append("\n");
        str.append("State = ")
               .append(getState())
             .append("\n");
        str.append("Source = ")
               .append(getSource())
             .append("\n");
        str.append("FeedbackDate = ")
               .append(getFeedbackDate())
             .append("\n");
        str.append("Type = ")
               .append(getType())
             .append("\n");
        str.append("Count = ")
               .append(getCount())
             .append("\n");
        return(str.toString());
    }
}
