package com.youku.soku.manage.torque;


import org.apache.torque.om.Persistent;

/**
 * 编辑操作
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed May 26 17:47:10 CST 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class DataOperation
    extends com.youku.soku.manage.torque.BaseDataOperation
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1274867230727L;

}
