package com.youku.soku.manage.torque;

/**
 * the search result of the interven keyword
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Jan 27 10:11:32 CST 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class KeywordIntervenVideoPeer
    extends com.youku.soku.manage.torque.BaseKeywordIntervenVideoPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1264558292828L;

}
