package com.youku.soku.manage.torque;

/**
 * 屏蔽词分类
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Sep 01 18:23:10 CST 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ShieldCategoryPeer
    extends com.youku.soku.manage.torque.BaseShieldCategoryPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1283336590645L;

}
