package com.youku.soku.manage.torque;


import org.apache.torque.om.Persistent;

/**
 * ·´À¡
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jun 13 16:33:58 CST 2011]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class SokuFeedbackUnion
    extends com.youku.soku.manage.torque.BaseSokuFeedbackUnion
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1307954038965L;

}
