package com.youku.soku.manage.torque;

/**
 * ·´À¡
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jun 13 16:26:37 CST 2011]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class SokuFeedbackPeer
    extends com.youku.soku.manage.torque.BaseSokuFeedbackPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1307953597808L;

}
