package com.youku.soku.manage.torque;


import org.apache.torque.om.Persistent;

/**
 * Video
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 21 10:17:37 CST 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Video
    extends com.youku.soku.manage.torque.BaseVideo
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1271816257912L;

}
