package com.youku.soku.manage.questionnaire.orm;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * 用户资料
 *
 * This class was autogenerated by Torque on:
 *
 * [Tue Jul 05 22:39:54 CST 2011]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to User
 */
public abstract class BaseUser extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1309876794856L;

    /** The Peer class */
    private static final UserPeer peer =
        new UserPeer();


    /** The value for the id field */
    private int id;

    /** The value for the name field */
    private String name;

    /** The value for the sex field */
    private int sex;

    /** The value for the age field */
    private int age;

    /** The value for the education field */
    private int education;

    /** The value for the area field */
    private int area;

    /** The value for the profession field */
    private int profession;

    /** The value for the phone field */
    private String phone;

    /** The value for the email field */
    private String email;


    /**
     * Get the Id
     *
     * @return int
     */
    public int getId()
    {
        return id;
    }


    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(int v) 
    {

        if (this.id != v)
        {
            this.id = v;
            setModified(true);
        }


    }

    /**
     * Get the Name
     *
     * @return String
     */
    public String getName()
    {
        return name;
    }


    /**
     * Set the value of Name
     *
     * @param v new value
     */
    public void setName(String v) 
    {

        if (!ObjectUtils.equals(this.name, v))
        {
            this.name = v;
            setModified(true);
        }


    }

    /**
     * Get the Sex
     *
     * @return int
     */
    public int getSex()
    {
        return sex;
    }


    /**
     * Set the value of Sex
     *
     * @param v new value
     */
    public void setSex(int v) 
    {

        if (this.sex != v)
        {
            this.sex = v;
            setModified(true);
        }


    }

    /**
     * Get the Age
     *
     * @return int
     */
    public int getAge()
    {
        return age;
    }


    /**
     * Set the value of Age
     *
     * @param v new value
     */
    public void setAge(int v) 
    {

        if (this.age != v)
        {
            this.age = v;
            setModified(true);
        }


    }

    /**
     * Get the Education
     *
     * @return int
     */
    public int getEducation()
    {
        return education;
    }


    /**
     * Set the value of Education
     *
     * @param v new value
     */
    public void setEducation(int v) 
    {

        if (this.education != v)
        {
            this.education = v;
            setModified(true);
        }


    }

    /**
     * Get the Area
     *
     * @return int
     */
    public int getArea()
    {
        return area;
    }


    /**
     * Set the value of Area
     *
     * @param v new value
     */
    public void setArea(int v) 
    {

        if (this.area != v)
        {
            this.area = v;
            setModified(true);
        }


    }

    /**
     * Get the Profession
     *
     * @return int
     */
    public int getProfession()
    {
        return profession;
    }


    /**
     * Set the value of Profession
     *
     * @param v new value
     */
    public void setProfession(int v) 
    {

        if (this.profession != v)
        {
            this.profession = v;
            setModified(true);
        }


    }

    /**
     * Get the Phone
     *
     * @return String
     */
    public String getPhone()
    {
        return phone;
    }


    /**
     * Set the value of Phone
     *
     * @param v new value
     */
    public void setPhone(String v) 
    {

        if (!ObjectUtils.equals(this.phone, v))
        {
            this.phone = v;
            setModified(true);
        }


    }

    /**
     * Get the Email
     *
     * @return String
     */
    public String getEmail()
    {
        return email;
    }


    /**
     * Set the value of Email
     *
     * @param v new value
     */
    public void setEmail(String v) 
    {

        if (!ObjectUtils.equals(this.email, v))
        {
            this.email = v;
            setModified(true);
        }


    }

       
        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("Id");
            fieldNames.add("Name");
            fieldNames.add("Sex");
            fieldNames.add("Age");
            fieldNames.add("Education");
            fieldNames.add("Area");
            fieldNames.add("Profession");
            fieldNames.add("Phone");
            fieldNames.add("Email");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Id"))
        {
            return new Integer(getId());
        }
        if (name.equals("Name"))
        {
            return getName();
        }
        if (name.equals("Sex"))
        {
            return new Integer(getSex());
        }
        if (name.equals("Age"))
        {
            return new Integer(getAge());
        }
        if (name.equals("Education"))
        {
            return new Integer(getEducation());
        }
        if (name.equals("Area"))
        {
            return new Integer(getArea());
        }
        if (name.equals("Profession"))
        {
            return new Integer(getProfession());
        }
        if (name.equals("Phone"))
        {
            return getPhone();
        }
        if (name.equals("Email"))
        {
            return getEmail();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Id"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Name"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setName((String) value);
            return true;
        }
        if (name.equals("Sex"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setSex(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Age"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setAge(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Education"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setEducation(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Area"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setArea(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Profession"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setProfession(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Phone"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPhone((String) value);
            return true;
        }
        if (name.equals("Email"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEmail((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(UserPeer.ID))
        {
            return new Integer(getId());
        }
        if (name.equals(UserPeer.NAME))
        {
            return getName();
        }
        if (name.equals(UserPeer.SEX))
        {
            return new Integer(getSex());
        }
        if (name.equals(UserPeer.AGE))
        {
            return new Integer(getAge());
        }
        if (name.equals(UserPeer.EDUCATION))
        {
            return new Integer(getEducation());
        }
        if (name.equals(UserPeer.AREA))
        {
            return new Integer(getArea());
        }
        if (name.equals(UserPeer.PROFESSION))
        {
            return new Integer(getProfession());
        }
        if (name.equals(UserPeer.PHONE))
        {
            return getPhone();
        }
        if (name.equals(UserPeer.EMAIL))
        {
            return getEmail();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (UserPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
      if (UserPeer.NAME.equals(name))
        {
            return setByName("Name", value);
        }
      if (UserPeer.SEX.equals(name))
        {
            return setByName("Sex", value);
        }
      if (UserPeer.AGE.equals(name))
        {
            return setByName("Age", value);
        }
      if (UserPeer.EDUCATION.equals(name))
        {
            return setByName("Education", value);
        }
      if (UserPeer.AREA.equals(name))
        {
            return setByName("Area", value);
        }
      if (UserPeer.PROFESSION.equals(name))
        {
            return setByName("Profession", value);
        }
      if (UserPeer.PHONE.equals(name))
        {
            return setByName("Phone", value);
        }
      if (UserPeer.EMAIL.equals(name))
        {
            return setByName("Email", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getId());
        }
        if (pos == 1)
        {
            return getName();
        }
        if (pos == 2)
        {
            return new Integer(getSex());
        }
        if (pos == 3)
        {
            return new Integer(getAge());
        }
        if (pos == 4)
        {
            return new Integer(getEducation());
        }
        if (pos == 5)
        {
            return new Integer(getArea());
        }
        if (pos == 6)
        {
            return new Integer(getProfession());
        }
        if (pos == 7)
        {
            return getPhone();
        }
        if (pos == 8)
        {
            return getEmail();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("Id", value);
        }
    if (position == 1)
        {
            return setByName("Name", value);
        }
    if (position == 2)
        {
            return setByName("Sex", value);
        }
    if (position == 3)
        {
            return setByName("Age", value);
        }
    if (position == 4)
        {
            return setByName("Education", value);
        }
    if (position == 5)
        {
            return setByName("Area", value);
        }
    if (position == 6)
        {
            return setByName("Profession", value);
        }
    if (position == 7)
        {
            return setByName("Phone", value);
        }
    if (position == 8)
        {
            return setByName("Email", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(UserPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    UserPeer.doInsert((User) this, con);
                    setNew(false);
                }
                else
                {
                    UserPeer.doUpdate((User) this, con);
                }
            }

            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
        setId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
        setId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public User copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public User copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public User copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new User(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public User copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new User(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected User copyInto(User copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected User copyInto(User copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected User copyInto(User copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setName(name);
        copyObj.setSex(sex);
        copyObj.setAge(age);
        copyObj.setEducation(education);
        copyObj.setArea(area);
        copyObj.setProfession(profession);
        copyObj.setPhone(phone);
        copyObj.setEmail(email);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected User copyInto(User copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setName(name);
        copyObj.setSex(sex);
        copyObj.setAge(age);
        copyObj.setEducation(education);
        copyObj.setArea(area);
        copyObj.setProfession(profession);
        copyObj.setPhone(phone);
        copyObj.setEmail(email);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public UserPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return UserPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("User:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("Name = ")
           .append(getName())
           .append("\n");
        str.append("Sex = ")
           .append(getSex())
           .append("\n");
        str.append("Age = ")
           .append(getAge())
           .append("\n");
        str.append("Education = ")
           .append(getEducation())
           .append("\n");
        str.append("Area = ")
           .append(getArea())
           .append("\n");
        str.append("Profession = ")
           .append(getProfession())
           .append("\n");
        str.append("Phone = ")
           .append(getPhone())
           .append("\n");
        str.append("Email = ")
           .append(getEmail())
           .append("\n");
        return(str.toString());
    }
}
