package com.youku.soku.index.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Tue Aug 25 17:23:05 CST 2009]
  *
  */
public class MovielogMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "com.youku.soku.index.om.map.MovielogMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("so");

        dbMap.addTable("movieLog");
        TableMap tMap = dbMap.getTable("movieLog");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);

        tMap.setPrimaryKeyMethodInfo("movieLog");

              tMap.addPrimaryKey("movieLog.ID", new Integer(0) );
                        	          tMap.addColumn("movieLog.TABLENAME", "", 50 );
                                      	          tMap.addColumn("movieLog.VID", new Integer(0), 11 );
                                      	          tMap.addColumn("movieLog.STATE", "", 50 );
                                        tMap.addColumn("movieLog.UPDATETIME", new Date() );
                }
}
