
package com.youku.soku.index.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Jul 28 14:59:04 CST 2009]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Affect
    extends com.youku.soku.index.om.BaseAffect
    implements Persistent
{
}
