package com.youku.soku.index.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;



          

/**
 * վ���
 *
 * This class was autogenerated by Torque on:
 *
 * [Tue Aug 25 17:23:05 CST 2009]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Site
 */
public abstract class BaseSite extends BaseObject
{
    /** The Peer class */
    private static final SitePeer peer =
        new SitePeer();

        
    /** The value for the id field */
    private int id;
      
    /** The value for the name field */
    private String name;
      
    /** The value for the tablename field */
    private String tablename;
                                          
    /** The value for the weight field */
    private double weight = 1;
                                          
    /** The value for the statusId field */
    private int statusId = 1;
  
            
    /**
     * Get the Id
     *
     * @return int
     */
    public int getId()
    {
        return id;
    }

                        
    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(int v) 
    {
    
                  if (this.id != v)
              {
            this.id = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Name
     *
     * @return String
     */
    public String getName()
    {
        return name;
    }

                        
    /**
     * Set the value of Name
     *
     * @param v new value
     */
    public void setName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.name, v))
              {
            this.name = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Tablename
     *
     * @return String
     */
    public String getTablename()
    {
        return tablename;
    }

                        
    /**
     * Set the value of Tablename
     *
     * @param v new value
     */
    public void setTablename(String v) 
    {
    
                  if (!ObjectUtils.equals(this.tablename, v))
              {
            this.tablename = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Weight
     *
     * @return double
     */
    public double getWeight()
    {
        return weight;
    }

                        
    /**
     * Set the value of Weight
     *
     * @param v new value
     */
    public void setWeight(double v) 
    {
    
                  if (this.weight != v)
              {
            this.weight = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the StatusId
     *
     * @return int
     */
    public int getStatusId()
    {
        return statusId;
    }

                        
    /**
     * Set the value of StatusId
     *
     * @param v new value
     */
    public void setStatusId(int v) 
    {
    
                  if (this.statusId != v)
              {
            this.statusId = v;
            setModified(true);
        }
    
          
              }
  
         
                
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("Id");
              fieldNames.add("Name");
              fieldNames.add("Tablename");
              fieldNames.add("Weight");
              fieldNames.add("StatusId");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("Id"))
        {
                return new Integer(getId());
            }
          if (name.equals("Name"))
        {
                return getName();
            }
          if (name.equals("Tablename"))
        {
                return getTablename();
            }
          if (name.equals("Weight"))
        {
                return new Double(getWeight());
            }
          if (name.equals("StatusId"))
        {
                return new Integer(getStatusId());
            }
          return null;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(SitePeer.ID))
        {
                return new Integer(getId());
            }
          if (name.equals(SitePeer.NAME))
        {
                return getName();
            }
          if (name.equals(SitePeer.TABLENAME))
        {
                return getTablename();
            }
          if (name.equals(SitePeer.WEIGHT))
        {
                return new Double(getWeight());
            }
          if (name.equals(SitePeer.STATUS_ID))
        {
                return new Integer(getStatusId());
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getId());
            }
              if (pos == 1)
        {
                return getName();
            }
              if (pos == 2)
        {
                return getTablename();
            }
              if (pos == 3)
        {
                return new Double(getWeight());
            }
              if (pos == 4)
        {
                return new Integer(getStatusId());
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(SitePeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    SitePeer.doInsert((Site) this, con);
                    setNew(false);
                }
                else
                {
                    SitePeer.doUpdate((Site) this, con);
                }
                }

                      alreadyInSave = false;
        }
      }

                  
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
            setId(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
            setId(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getId());
      }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public Site copy() throws TorqueException
    {
        return copyInto(new Site());
    }
  
    protected Site copyInto(Site copyObj) throws TorqueException
    {
          copyObj.setId(id);
          copyObj.setName(name);
          copyObj.setTablename(tablename);
          copyObj.setWeight(weight);
          copyObj.setStatusId(statusId);
  
                            copyObj.setId( 0);
                                    
                return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public SitePeer getPeer()
    {
        return peer;
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Site:\n");
        str.append("Id = ")
               .append(getId())
             .append("\n");
        str.append("Name = ")
               .append(getName())
             .append("\n");
        str.append("Tablename = ")
               .append(getTablename())
             .append("\n");
        str.append("Weight = ")
               .append(getWeight())
             .append("\n");
        str.append("StatusId = ")
               .append(getStatusId())
             .append("\n");
        return(str.toString());
    }
}
