package com.youku.soku.index.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;



          

/**
 * ��������
 *
 * This class was autogenerated by Torque on:
 *
 * [Wed Jul 29 11:58:40 CST 2009]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Affect
 */
public abstract class BaseAffect extends BaseObject
{
    /** The Peer class */
    private static final AffectPeer peer =
        new AffectPeer();

        
    /** The value for the id field */
    private int id;
      
    /** The value for the site field */
    private int site;
      
    /** The value for the vid field */
    private int vid;
      
    /** The value for the operate field */
    private int operate;
      
    /** The value for the createTime field */
    private Date createTime;
  
            
    /**
     * Get the Id
     *
     * @return int
     */
    public int getId()
    {
        return id;
    }

                        
    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(int v) 
    {
    
                  if (this.id != v)
              {
            this.id = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Site
     *
     * @return int
     */
    public int getSite()
    {
        return site;
    }

                        
    /**
     * Set the value of Site
     *
     * @param v new value
     */
    public void setSite(int v) 
    {
    
                  if (this.site != v)
              {
            this.site = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Vid
     *
     * @return int
     */
    public int getVid()
    {
        return vid;
    }

                        
    /**
     * Set the value of Vid
     *
     * @param v new value
     */
    public void setVid(int v) 
    {
    
                  if (this.vid != v)
              {
            this.vid = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Operate
     *
     * @return int
     */
    public int getOperate()
    {
        return operate;
    }

                        
    /**
     * Set the value of Operate
     *
     * @param v new value
     */
    public void setOperate(int v) 
    {
    
                  if (this.operate != v)
              {
            this.operate = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the CreateTime
     *
     * @return Date
     */
    public Date getCreateTime()
    {
        return createTime;
    }

                        
    /**
     * Set the value of CreateTime
     *
     * @param v new value
     */
    public void setCreateTime(Date v) 
    {
    
                  if (!ObjectUtils.equals(this.createTime, v))
              {
            this.createTime = v;
            setModified(true);
        }
    
          
              }
  
         
                
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("Id");
              fieldNames.add("Site");
              fieldNames.add("Vid");
              fieldNames.add("Operate");
              fieldNames.add("CreateTime");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("Id"))
        {
                return new Integer(getId());
            }
          if (name.equals("Site"))
        {
                return new Integer(getSite());
            }
          if (name.equals("Vid"))
        {
                return new Integer(getVid());
            }
          if (name.equals("Operate"))
        {
                return new Integer(getOperate());
            }
          if (name.equals("CreateTime"))
        {
                return getCreateTime();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(AffectPeer.ID))
        {
                return new Integer(getId());
            }
          if (name.equals(AffectPeer.SITE))
        {
                return new Integer(getSite());
            }
          if (name.equals(AffectPeer.VID))
        {
                return new Integer(getVid());
            }
          if (name.equals(AffectPeer.OPERATE))
        {
                return new Integer(getOperate());
            }
          if (name.equals(AffectPeer.CREATE_TIME))
        {
                return getCreateTime();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getId());
            }
              if (pos == 1)
        {
                return new Integer(getSite());
            }
              if (pos == 2)
        {
                return new Integer(getVid());
            }
              if (pos == 3)
        {
                return new Integer(getOperate());
            }
              if (pos == 4)
        {
                return getCreateTime();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(AffectPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    AffectPeer.doInsert((Affect) this, con);
                    setNew(false);
                }
                else
                {
                    AffectPeer.doUpdate((Affect) this, con);
                }
                }

                      alreadyInSave = false;
        }
      }

                  
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
            setId(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
            setId(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getId());
      }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public Affect copy() throws TorqueException
    {
        return copyInto(new Affect());
    }
  
    protected Affect copyInto(Affect copyObj) throws TorqueException
    {
          copyObj.setId(id);
          copyObj.setSite(site);
          copyObj.setVid(vid);
          copyObj.setOperate(operate);
          copyObj.setCreateTime(createTime);
  
                            copyObj.setId( 0);
                                    
                return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public AffectPeer getPeer()
    {
        return peer;
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Affect:\n");
        str.append("Id = ")
               .append(getId())
             .append("\n");
        str.append("Site = ")
               .append(getSite())
             .append("\n");
        str.append("Vid = ")
               .append(getVid())
             .append("\n");
        str.append("Operate = ")
               .append(getOperate())
             .append("\n");
        str.append("CreateTime = ")
               .append(getCreateTime())
             .append("\n");
        return(str.toString());
    }
}
