var o=null;function q(c){return function(h){this[c]=h}}var r=window.gc||{};r.global=this;window.Ab=t;window.changeSearchType=u;function t(c,h){if(r)r.aa.prototype.La=function(){this.i.className="main";r.f.show(this.i);this.D=!0;this.g=-1},aa=new r.aa(c,"headq","aa","http://tip.soku.com/search_keys"),h&&(aa.Mb("&site=2"),aa.Ka("/search_video/q_")),aa.Kb("http://lstat.youku.com"),aa.Lb("")}function u(c){aa&&aa.Ka(c)}
(function(c){function h(a){if("string"==typeof a||a instanceof String)return document.getElementById(a);else if(a&&a.nodeName&&(a.nodeType==1||a.nodeType==9))return a;return o}trim=String.prototype.trim?function(a){return a==o?"":String.prototype.trim.call(a)}:function(a){return a==o?"":a.toString().replace(/^[\s\xA0]+/,"").replace(/[\s\xA0]+$/,"")};gc=function(a,b){var c,d=[],f,i,m,p;if(!(a=trim(a)))return o;if("undefined"==typeof b)b=document;else if(b=h(b),!b)return d;c&&(c=trim(c).toUpperCase());
if(b.getElementsByClassName){m=b.getElementsByClassName(a);f=m.length;for(i=0;i<f;i++)p=m[i],c&&p.tagName!=c||(d[d.length]=p)}else{a=RegExp("(^|\\s)"+a+"(\\s|$)");m=c?b.getElementsByTagName(c):b.all||b.getElementsByTagName("*");f=m.length;for(i=0;i<f;i++)p=m[i],a.test(p.className)&&(d[d.length]=p)}return d};c.extend=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};c.bind=function(a,b){var c=arguments.length>2?Array.prototype.slice.call(arguments,2):o;return function(){var d="[object String]"==
Object.prototype.toString.call(a)?b[a]:a,f=c?c.concat(Array.prototype.slice.call(arguments,0)):arguments;return d.apply(b||d,f)}};c.e={element:function(a){return a.target||a.srcElement},h:function(a,b,c,d){if(b=="keypress"&&(navigator.appVersion.match(/Konqueror|Safari|KHTML/)||a.attachEvent))b="keydown";a.addEventListener?a.addEventListener(b,c,d):a.attachEvent&&(a["e"+b+c]=c,a[b+c]=function(){return a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c]))}};c.f={lc:function(a){return h(a).style.display!=
"none"},n:function(){for(var a=0;a<arguments.length;a++)h(arguments[a]).style.display="none"},show:function(){for(var a=0;a<arguments.length;a++)h(arguments[a]).style.display="block"},Zb:function(a){a=h(a);return a.offsetHeight},S:function(a,b){if(a=h(a))a.className=""==a.className?b:a.className+" "+b},Y:function(a,b){if(a=h(a))a.className=a.className.replace(RegExp("(^| )"+b+"( |$)"),"$1").replace(/ $/,"")},ga:function(a,b,c){var d=b;if(typeof b==="string")if(c===void 0)return a&&a.getAttribute(b);
else d={},d[b]=c;for(var f in d)a.setAttribute(f,d[f])}};c.fb={Sa:8,ib:9,bb:13,Wa:27,Za:37,jb:38,cb:39,Ua:40,Tb:46,ab:33,$a:34,Va:35,Xa:36,Ya:45,eb:16,Ta:17,Ra:18};c.aa=function(a,b,e,d){a||c.e.h(document,"click",c.bind(this.za,this));c.e.h(document,"blur",c.bind(this.za,this));this.fa={};this.Ga=this.pb;if(e)this.Ga=e;this.X=navigator&&navigator.userAgent.toLowerCase().indexOf("msie")!=-1;this.a=document.getElementById(b);c.e.h(this.a,"keypress",c.bind(this.onkeydown,this));var f=this;this.v=c.global.VideoWall;
this.xa=0;this.a.onblur=function(){a&&VideoWall&&VideoWall.show();f.n()};a?c.e.h(this.a,"focus",c.bind(this.focus,this)):c.e.h(this.a,"dblclick",c.bind(this.lb,this));this.count=0;this.pa=this.wa;this.Na=this.hb;if(d)this.pa=d;this.Ma="";this.Da=this.wa;this.Ea=this.gb;this.Ja=this.ob;this.Ia=this.nb;this.$b="";this.Bb=this.mb+this.da;this.la=!1;this.ia=this.J=!0;this.R=document.createElement("div");document.body.appendChild(this.R);this.i=document.createElement("div");c.f.n(this.i);document.getElementById("kubox").appendChild(this.i);
this.U=document.createElement("div");this.U.className="panels";this.ta=document.createElement("div");this.ta.className="all";document.getElementById("kubox").appendChild(this.ta);this.z=document.createElement("div");this.D=!1;this.I=this.C="";if(this.a&&this.a.value!="")this.I=this.a.value;this.G=this.I;this.$=!1;this.ja=!0;this.Q=-1;this.V=this.Xb=0;if(a)this.A=document.getElementById("canplay"),c.e.h(this.A,"mouseover",c.bind(this.ma,this)),c.f.n(this.A);this.ka=a;window.onresize=c.bind(this.Rb,
this);this.L();this.na=1;if(this.a)this.K=setTimeout(c.bind(this.oa,this),this.ea)};c.extend(c.aa.prototype,{start:function(){this.K!=0&&clearTimeout(this.K);this.K=setTimeout(c.bind(this.oa,this),this.ea);if(this.a&&this.a.value!="")this.G=this.I=this.a.value},bc:q("na"),fc:q("v"),cc:q("Ga"),ec:function(a,b){this.pa=a;if(b)this.Na=b;this.L()},Mb:q("Ma"),Kb:function(a,b){this.Da=a;if(b)this.Ea=b},Lb:q("Ja"),ac:function(a){this.Bb=a.indexOf(this.da)>0?a:a+this.da},dc:function(){this.la=!0},Ka:q("Ia"),
ub:function(a){return encodeURI(this.Ja+this.Ia+a)},vb:function(a){return encodeURI(this.pa+this.Na+a+this.Ma+this.wb())},F:function(a,b,e,d){if(c.global.sokuClickStat){var f={};f._log_type=a;f._log_site=this.na;f._log_pos=b;f.keyword=e;d||(d=c.global.location.href);f._log_url=d;c.global.sokuClickStat(f)}else f="",a&&(f+=a),b&&(f+="&pos="+b),e&&(f+="&keyword="+e),d||(d=c.global.location.href),d&&(f+="&url="+encodeURIComponent(d)),(new Image).src=encodeURI(this.Da+this.Ea+f+"&site="+this.na+"&rand"+
Math.round(Math.random()*2147483647))},Jb:function(){var a=this;this.a.onblur=function(){a.ka&&a.v&&a.v.show();a.n()}},lb:function(){if(this.a.createTextRange){var a=this.a.createTextRange();a.moveStart("character",0);a.select()}else this.a.setSelectionRange&&this.a.setSelectionRange(0,this.a.value.length);this.J&&this.a.value!=""&&(this.C==this.a.value?this.i.innerHTML!=""&&this.show():this.M())},focus:function(){this.Jb();this.ka&&(navigator.userAgent.match(/msie/i)?this.xa>0&&this.v&&this.v.hide():
this.v&&this.v.hide());this.xa++;this.J&&this.ja&&this.a.value!=""&&(this.C==this.a.value?this.i.innerHTML!=""&&this.show():this.M())},Z:function(){return this.Q!=-1},Rb:function(){this.D&&this.show()},onkeydown:function(a){this.ka&&this.v&&this.v.hide();if(a.ctrlKey)return!0;var b=c.fb;switch(a.keyCode){case b.ab:case b.$a:case b.Va:case b.Xa:case b.Ya:case b.Ta:case b.Ra:case b.Za:if(this.Z())this.Q=-1,this.N();return!0;case b.cb:if(a=document.getElementById("ddiv"+this.g))return this.va=gc("item",
a),this.V=this.va.length,this.Q=this.g,this.o=0,this.P(),!0;a=this.w(this.B(),this.ca);b=this.w(this.B(),this.s);if(a&&a.length>0)return this.F(4,3,b,a),window.location=a,!1;return!0;case b.eb:case b.ib:return!0;case b.Wa:return this.ja=!1,this.n(),!1;case b.jb:if(this.D)this.Z()?this.zb():(this.$=!0,this.Nb());else{if(this.i.childNodes.length>1&&this.C==this.a.value&&this.J)return this.show(),!1;this.a.value!=""&&this.M()}this.X?a.returnValue=!1:a.preventDefault();return!1;case b.Ua:if(this.D)this.Z()?
this.yb():(this.$=!0,this.qb());else{if(this.i.childNodes.length>1&&this.C==this.a.value&&this.J)return this.show(),!1;this.a.value!=""&&this.M()}this.X?a.returnValue=!1:a.preventDefault();return!1;case b.bb:if(this.Z())return b=this.w(this.B(),this.s),this.F(4,2,b,this.ua),window.location.href=this.ua,this.X?a.returnValue=!1:a.preventDefault(),!1;if(this.D&&this.g>-1&&!this.select())return this.X?a.returnValue=!1:a.preventDefault(),!1;case b.Sa:if(this.a.value.length==1)this.G="";default:return this.$=
!1,!0}},oa:function(){if(!(document.activeElement&&document.activeElement!=this.a))if(this.a.value!=""&&this.a.value!=this.I)this.C!=this.a.value&&(this.$||this.M());else if(this.C!="")this.C="",this.D&&(this.n(),this.L());this.K!=0&&clearTimeout(this.K);this.K=setTimeout(c.bind(this.oa,this),this.ea)},Ba:function(a,b,c){c.stopPropagation?c.stopPropagation():c.cancelBubble=!0;this.F(4,3,a,b)},Qa:function(a,b){this.F(4,2,a,b)},Qb:function(a,b){this.F(4,3,a,b)},Pb:function(a,b){this.F(5,1,a,b)},select:function(a){if(this.B()){this.B().getAttribute(this.ra);
var b=this.w(this.B(),this.s);try{if(a){if(this.G=b,!this.la)this.a.value=b}else{if(this.a.value!=b)return!0;this.G=b;b=this.a.value}this.F(4,1,b);this.n();var c=this.ub(b);this.la?window.open(c,"_blank"):document.location=c}catch(d){}}return!1},M:function(){if(this.J){this.I="";var a=this.a.value;this.C=this.G=a;a.length>15||(this.fa[a]?this.suggestUpdate(this.fa[a]):this.sb(this.vb(a),a))}},L:function(){this.size=0;this.g=-1;this.i.innerHTML="";this.z.innerHTML=""},Ib:function(){setTimeout(c.bind(this.Ob,
this),5)},kb:function(){for(;this.R.childNodes.length>0;)this.R.removeChild(this.R.firstChild)},Aa:function(a){return a.nodeType==1},W:function(a){if(a&&a.getElementsByTagName("div").length>0)return this.w(a.getElementsByTagName("div")[0],this.sa);return o},w:function(a,b){if(a&&a.getAttribute(b))return this.unescape(a.getAttribute(b))},Ob:function(){this.kb();var a=this.a.value;if(this.z.innerHTML=="")this.i.innerHTML!=""&&this.W(this.i)==a||(this.n(),this.L());else if(this.W(this.z)!=a&&a!="")this.i.innerHTML!=
""&&this.W(this.i)==a||this.n();else{for(var b,e=!1,d=this.z.getElementsByTagName("div")[0].getElementsByTagName("li"),a=0;a<d.length;a++)if(b=d[a],this.Aa(b)){e=!0;break}if(e){this.i.innerHTML=this.z.innerHTML;d=this.i.getElementsByTagName("div")[0].getElementsByTagName("li");this.size=0;this.T=[];for(a=0;a<d.length;a++)if(b=d[a],this.Aa(b)){b.setAttribute(this.ba,this.size);c.e.h(b,"mousemove",c.bind(this.Eb,this));c.e.h(b,"mouseover",c.bind(this.Fa,this));c.e.h(b,"mouseout",c.bind(this.Gb,this));
c.e.h(b,"click",c.bind(this.select,this));var f=b.getElementsByTagName("a"),e=this.w(b,this.s);f[0]&&c.e.h(f[0],"click",c.bind(this.Ba,this,e,f[0].href),!0);f[1]&&c.e.h(f[1],"click",c.bind(this.Ba,this,e,f[0].href),!0);this.T.push(b);this.size++}this.show();this.ha=!1;for(a=0;a<10;a++)if(e=document.getElementById("ddiv"+a)){c.e.h(e,"mouseover",c.bind(this.ma,this));c.e.h(e,"mouseout",c.bind(this.Ha,this));b=gc("item",e);if(e.attachEvent)for(d=0;d<b.length;d++)c.e.h(b[d],"mouseenter",c.bind(this.Cb,
this)),c.e.h(b[d],"mouseleave",c.bind(this.Db,this));else for(d=0;d<b.length;d++)c.e.h(b[d],"mouseover",c.bind(this.Hb,this)),c.e.h(b[d],"mouseout",c.bind(this.Fb,this));e=this.w(e,"itemq");for(d=0;d<b.length;d++){var f=gc("baseinfo",b[d]),i=gc("thumb",b[d]),m=f[0].getElementsByTagName("a")[0].href;f&&(c.e.h(f[0].getElementsByTagName("a")[0],"click",c.bind(this.Qa,this,e,m)),c.e.h(i[0].getElementsByTagName("img")[0],"click",c.bind(this.Qa,this,e,m)));(f=gc("play",b[d]))&&c.e.h(f[0].getElementsByTagName("a")[0],
"click",c.bind(this.Qb,this,e,f[0].getElementsByTagName("a")[0].href))}}if(a=h("ddiv0"))c.f.show(a),c.f.show(a.parentNode),this.Ca(a)}else this.n(),this.L()}},La:function(){c.f.show(this.i);this.D=!0;this.g=-1},show:function(){c.f.show(h("kubox"));this.i.childNodes.length<1||(!this.J||!(this.a.value!=""&&this.W(this.i)!=this.a.value))&&this.La()},n:function(){this.H();c.f.n(this.i);c.f.n(h("kubox"));this.g=-1;this.D=!1},za:function(){if(this.ia)this.n(),this.ia=!1,setTimeout(c.bind(this.rb,this),
60)},rb:function(){this.ia=!0},Eb:function(a){this.ha=!0;this.Fa(a)},Fa:function(a){this.ma();if(this.ha){for(a=c.e.element(a);a.parentNode&&(!a.tagName||a.getAttribute(this.ba)==o);)a=a.parentNode;a=a.tagName?a.getAttribute(this.ba):-1;if(!(a==-1||a==this.g))this.H(),this.g=Number(a),this.O(!1)}else this.ha=!0},Gb:function(){this.H();this.g=-1;this.Ha()},tb:function(a){if(this.T&&a>=0&&a<this.T.length)return this.T[a]},B:function(){return this.tb(this.g)},xb:function(a,b){if(!a)this.a.value=b},Ca:function(a){for(var a=
a.getElementsByTagName("img"),b=0;b<a.length;b++)a[b].setAttribute("src",a[b].getAttribute("_src"))},O:function(a){var b=this.B(),e;if(b){c.f.S(b,this.qa);try{e=this.w(b,this.s);this.xb(!a,e);var d=this.w(b,this.ca);a&&this.Pa(d)}catch(f){}}for(a=0;a<10;a++)if(e=h("ddiv"+a))if(a==this.g){c.f.show(e);c.f.show(e.parentNode);this.Ca(e);b=289-e.getAttribute("itemC")*90;e=e.getElementsByTagName("div");for(d=0;d<e.length;d++)if(e[d]&&e[d].className&&e[d].className=="item"){var i=this.g;e[d].style.top=(i*
28>b?b:i*28)+"px"}}else this.Q=-1,c.f.n(e)},H:function(){var a=this.B();a&&c.f.Y(a,this.qa)},Nb:function(){var a=this.g;this.g>0?(this.H(),this.g=a-1,this.O(!0)):this.g==0?(this.H(),this.g=a-1,this.a.value=this.G):(this.g=this.size-1,this.O(!0))},qb:function(){var a=this.g;this.g<0?(this.g=a+1,this.O(!0)):this.g<this.size-1?(this.H(),this.g=a+1,this.O(!0)):(this.H(),this.g=-1,this.a.value=this.G)},zb:function(){var a=this.o;if(this.o>0)this.N(),this.o=a-1,this.P();else if(this.o==0)this.N(),this.o=
this.V-1,this.P()},yb:function(){var a=this.o;if(this.o<this.V-1)this.N(),this.o=a+1,this.P();else if(this.o==this.V-1)this.N(),this.o=0,this.P()},ya:function(){return this.va[this.o]},P:function(){var a=this.ya();this.ua=gc("baseinfo",a)[0].getElementsByTagName("a")[0].href;c.f.S(a,"current")},N:function(){c.f.Y(this.ya(),"current")},Hb:function(a){for(a=c.e.element(a);a&&a.nodeName!="BODY";)a=a.parentNode,a.className=="item"&&c.f.S(a,"current")},Fb:function(a){for(var b=c.e.element(a);b&&b.nodeName!=
"BODY";)if(b=b.parentNode,b.className.indexOf("item")>-1)break;(a.relatedTarget?a.relatedTarget:a.toElement)==b&&c.f.Y(b,"current")},Cb:function(a){a=c.e.element(a);c.f.S(a,"current")},Db:function(a){a=c.e.element(a);c.f.Y(a,"current")},sb:function(a){var b=document.createElement("script");b.src=a;this.R.appendChild(b)},unescape:function(a){return a.replace(RegExp("&quot;","gm"),'"').replace(RegExp("&gt;","gm"),">").replace(RegExp("&lt;","gm"),"<").replace(RegExp("&amp;","gm"),"&")},escape:function(a){return a.replace(RegExp("&",
"gm"),"&amp;").replace(RegExp("<","gm"),"&lt;").replace(RegExp(">","gm"),"&gt;").replace(RegExp('"',"gm"),"&quot;")},hc:function(a){if(a.length<=43)return a;return a.substr(a,40)+"..."},suggestUpdate:function(a){this.ja=!0;this.U.innerHTML="";this.z.innerHTML="";this.Q=-1;if(a&&typeof a==="object"){var b=a.q;this.fa[b]=a;this.Pa(a.p);if((a=a.r)&&a.length){var e=document.createElement("div");e.setAttribute(this.sa,this.escape(b));for(var d=document.createElement("ul"),f=document.createElement("ul"),i=0,h=0,p=
a.length;h<p;h++){var j=a[h],k=document.createElement("li"),i=j.c;J=0;var g=this.escape(i),s=g;j.t&&(J=j.t);var i=j.d,n=trim(b);g!=n&&g.indexOf(n)>-1&&(g=n+'<b style="font-weight:bold">'+g.substring(g.indexOf(n)+n.length)+"</b>");k.setAttribute(this.ra,J);if(J==0)i==1&&(g+="<span class='expand'>&gt;</span>"),k.innerHTML=g,c.f.ga(k,{"class":""}),d.appendChild(k),g=s.replace(/^\d+\. /,""),k.setAttribute(this.s,g),d.setAttribute(this.s,g);else if(J==1)k.setAttribute(this.s,s),k.setAttribute(this.ca,
this.escape(j.l)),g+="<a class='goplay' target='_blank' href='"+this.escape(j.l)+"'><em>\u64ad\u653e</em></a>",k.innerHTML=g,c.f.ga(k,{"class":""}),d.appendChild(k),s=s.replace(/^\d+. /,""),d.setAttribute(this.s,s);if(i==1){var k=document.createElement("div"),g=[],j=j.u,l;for(l in j)n=j[l].k,g.push("<div class='item' itemindex='"+l+"'>"),g.push("<div class='thumb'><a target='_blank' href='"),g.push(j[l].d),g.push("'><img _src='"),g.push(j[l].b),g.push("' /></a></div>"),g.push("<div class='baseinfo'><a target='_blank' href='"),
g.push(j[l].d),g.push("'>"),g.push(j[l].j+"</a><i>"),g.push(j[l].m),g.push("</i><i>"),g.push(j[l].y),g.push("</i>"),g.push("</div><div class='actor'>"),j[l].p&&j[l].p.length&&(g.push("\u4e3b\u6f14\uff1a "),g.push(j[l].p)),g.push("</div>"),g.push("<div class='play'>"),n&&n.length&&(g.push("<a target='_blank' href='"),g.push(n),g.push("'><em>\u64ad\u653e</em></a>")),g.push("</div>"),g.push("</div>");k.innerHTML=g.join("");k.setAttribute("id","ddiv"+h);k.setAttribute("itemC",j.length);k.setAttribute("itemq",
s);k.className="panel";this.U.appendChild(k)}c.f.ga(d,{"class":"autolist"});e.appendChild(d);i==1&&e.appendChild(f);this.z.appendChild(e);this.z.appendChild(this.U)}}}this.Ib()},kc:function(){},Pa:function(a){if(this.A)a&&a.length>0?(c.f.show(this.A),this.A.innerHTML="<a target='_blank' href='"+a+"'><em>\u64ad\u653e</em></a>",(a=this.A.getElementsByTagName("a"))&&c.e.h(a[0],"click",c.bind(this.Pb,this,keyword,url))):(c.f.n(this.A),this.A.innerHTML="")},Yb:function(){this.a.focus();if(this.a.createTextRange){var a=
this.a.createTextRange();a.moveStart("character",this.a.value.length);a.select()}else this.a.setSelectionRange&&this.a.setSelectionRange(this.a.value.length,this.a.value.length)},ma:function(){this.a.onblur=o},Ha:function(){this.a.onblur=c.bind(this.n,this)},jc:function(){return"&time="+new Date},wb:function(){return"&h="+(new Date).getHours()},Wb:"mouseSelect",Vb:"keySelect",Ub:"iconPress",Sb:"changeStatus",ea:50,ba:"autoindex",qa:"current",ra:"hitt",s:"hitq",ca:"hitl",sa:"squery",da:".suggest",
hb:"?query=",gb:"/sokuClick.php?type=",wa:"http://"+location.host+"/suggest/",ob:"http://"+document.domain+"/search?",nb:"/v?keyword=",mb:document.domain.replace(/.soku.com/,""),pb:"aa",ic:"SUG_STATUS"})})(r);
