var Filter={init:function(){this.conditions=$(".filter .item");this.conditions.length!=0&&this.bind()},bind:function(){this.conditions.each(function(){var a=$(this);a.find("li").each(function(){$(this).find("a").click(function(){var b=a.find("li.current");b.length!=0&&b.removeClass("current");$(this).parent().addClass("current");return!1})})})}},Selector={init:function(){this.selectors=$(".selector");this.selectors.length!=0&&this.bind()},bind:function(){$.each(this.selectors,function(){var a=$(this).find(".selected"),
b=$(this).find(".options"),c=b.attr("index"),d=$(this).find(".options").find("li"),e=b.find("[index="+c+"]");a.click(function(){b.toggle();return!1});$.each(d,function(){$(this).attr("index")==c&&$(this).addClass("current");$(this).find("a").click(function(){var d=$(this).parent(),g=d.attr("index");g!=c&&(a.html($(this).text()),e.removeClass("current"),d.addClass("current"),c=g,e=d,b.hide());return!1})})})}},ViewBy={init:function(){var a=$(".viewby");if(a.length!=0)this.bys=a.find("li"),this.vcoll=
$("#vcoll"),this.pcoll=$("#pcoll"),this.by=a.find(".current"),this.bind()},bind:function(){var a=this;this.bys.each(function(){$(this).click(function(){if($(this).attr("viewby")!=a.by.attr("viewby")){$(this).addClass("current");var b=$(this).attr("viewby");a.vcoll.length!=0&&(b=="list"?a.vcoll.addClass("colllist1w").removeClass("collgrid4w"):a.vcoll.addClass("collgrid4w").removeClass("colllist1w"));a.pcoll.length!=0&&(b=="list"?a.pcoll.addClass("colllist1w").removeClass("collgrid4w"):a.pcoll.addClass("collgrid4w").removeClass("colllist1w"));
a.by.length!=0&&a.by.removeClass("current")}a.by=$(this);writeCookie("viewby",a.by.attr("viewby"),8640)})})}},PartPop={init:function(){this.pophandles=$(".v .v_part");this.globalpop=$("#globalpop");this.pophandles.length!=0&&this.bind()},bind:function(){var a=this;$.each(this.pophandles,function(){var b=$(this).find(".handle"),c=$(this).find(".pop");$(this).mouseover(function(){a.globalpop.length==0&&a.create();$.each(c.find("img"),function(){var a=$(this).attr("_src");a&&($(this).attr("src",a),$(this).removeAttr("_src"))});
a.globalpop.html(c.html());var d=b.offset(),e=d.top-4,f=d.left+20;d.left+280+5>parseInt($(window).width())&&(f=d.left-280);a.globalpop.css({top:e,left:f});a.globalpop.show()});$(this).mouseout(function(){a.globalpop.hide()})})},create:function(){if(this.globalpop.length==0)this.globalpop=$('<div id="globalpop" class="pop"></div>'),$(document.body).append(this.globalpop),this.globalpop.mouseover(function(){$(this).show()}),this.globalpop.mouseout(function(){$(this).hide()})}},SpeedSelector={init:function(){var a=
$(".source .check label");$.each(a,function(){SpeedSelector.selectSite($(this),!1)});this.selectors=$(".gotoplay .source");this.bind()},bind:function(){$.each(this.selectors,function(){var a=$(this).find(".check"),b=$(this).find(".other"),c=b.find("li");$(this).click(function(){if(b.length!=0&&c.length!=0){for(var a,e=0;e<c.length;e++){a=!1;for(var f=c.length-2;f>=e;f--)parseInt($(c[f+1]).find("div").attr("class").substring(11))<parseInt($(c[f]).find("div").attr("class").substring(11))&&(a=c[f+1],
c[f+1]=c[f],c[f]=a,a=!0);if(!a)break}f=[];for(e=0;e<c.length;e++)f[e]=$(c[e]).html();a=b.find("li");for(e=0;e<a.length;e++)$(a[e]).html(f[f.length-1-e]);b.toggle()}return!1});$(document).bind("click",function(){b.hide()});$.each(c,function(){$(this).click(function(){var c=$(this).find("label"),e=$(this).parent().parent().parent().parent(),f=e.find(".linkpanels");$.each(f,function(){$(this).css("display","none")});e.find("."+c.attr("id")).css("display","");SpeedSelector.selectSite(c,!0);c=$(this).html();
e=a.html();a.html(c);$(this).html(e);b.hide();$(".source .check label").attr("id")!="site14"?$(".base_update").css("display","none"):$(".base_update").css("display","");return!1})})})},selectSite:function(a,b){var c=a.parent().parent().parent().parent().parent().parent();c.find(".p_status span.status").html(a.attr("title"));c.find(".p_ishd span").attr("class","ico__"+a.attr("stype"));c.find(".p_ishd span").attr("title",a.attr("stypename"));a.attr("title").length+a.attr("stype").length==0?c.find(".p_status span.bg").attr("class",
"bgd"):c.find(".p_status span.bgd").attr("class","bg");if(b){var d={_log_type:2,_log_pos:a.attr("_log_pos"),_log_ct:a.attr("_log_ct"),_log_directpos:8};sokuClickStat(d)}d=c.find(".linkpanels");$.each(d,function(){if($(this).css("display")!="none"){var a=$(this).find("ul").find("li").find("a");a.length>0&&(a=$(a[0]).attr("href"),c.find(".btnplay_large a").attr("href",a),c.find(".p_link_site a").attr("href",a))}})}},PanelExpand={init:function(){this.handles=$(".linkpanel .handle");this.handles.length!=
0&&this.bind()},bind:function(){$.each(this.handles,function(){$(this).click(function(){var a=$(this).parent().parent().find(".panelexpand");$(this).toggleClass("handleexpand");a.toggle();$.trim($(this).text())=="\u5168\u90e8"?$(this).html("<span>\u6536\u8d77</span>"):$(this).html("<span>\u5168\u90e8</span>");return!1})})}},FeedBack={init:function(){this.handles=$(".feedwin .handle");this.steps=$(".feedwin .step");this.handles.length!=0&&this.bind()},bind:function(){$(".feedwin .close").click(function(){$(".feedwin .feed").css("display",
"none");$.each($(".feedwin .step"),function(){$(this).css("display","block")});$(".feedwin .feed .like").removeClass("selected");$(".feedwin .feed .unlike").removeClass("selected");$(".feedwin  .feed .step3").css("display","none");$("#state").attr("value","");$("#message").attr("value","\u503e\u542c\u60a8\u7684\u5efa\u8bae(100\u5b57\u4ee5\u5185)");$("#message").css("color","#909090");$("#message").click(function(){$("#message").attr("value","");$("#message").css("color","#000000");$(this).unbind("click")})});
$("#message").click(function(){$("#message").attr("value","");$("#message").css("color","#000000");$(this).unbind("click")});this.handles.click(function(){$(".feedwin").find(".feed").toggle();$.each($(".feedwin .step"),function(){$(this).css("display","block")});$(".feedwin .feed .like").removeClass("selected");$(".feedwin .feed .unlike").removeClass("selected");$(".feedwin  .feed .step3").css("display","none");$("#message").css("color","#909090");$("#message").attr("value","\u503e\u542c\u60a8\u7684\u5efa\u8bae(100\u5b57\u4ee5\u5185)");
$("#state").attr("value","");$("#message").click(function(){$("#message").attr("value","");$("#message").css("color","#000000");$(this).unbind("click")});$(".feedwin .feed  .input button").html("\u63d0\u4ea4");$(".feedwin .feed  .input button").unbind("click");$(".feedwin .feed  .input button").click(function(){commitFeedbak()})});$(".feedwin .feed .like").click(function(){$("#state").attr("value",1);$(this).addClass("selected");$(".feedwin .feed .unlike").removeClass("selected")});$(".feedwin .feed .unlike").click(function(){$("#state").attr("value",
0);$(this).addClass("selected");$(".feedwin .feed .like").removeClass("selected")})}};
function commitFeedbak(){if($("#state").attr("value")!="1"&&$("#state").attr("value")!="0")return alert("\u8bf7\u9009\u62e9\u662f\u5426\u559c\u6b22"),!1;var a="";$("#message").attr("value")!="\u503e\u542c\u60a8\u7684\u5efa\u8bae(100\u5b57\u4ee5\u5185)"&&(a=$("#message").attr("value"));if(a.length>100)return alert("\u60a8\u7684\u8f93\u5165\u5df2\u7ecf\u8d85\u51fa\u9650\u5236\uff0c\u8bf7\u4fee\u6539\uff01"),!1;$.ajax({url:"/service/feedback",type:"POST",data:"keyword="+encodeURI($("#keyword").val())+
"&state="+$("#state").val()+"&url="+encodeURI(window.location.href)+"&message="+encodeURI(a)});$(".feedwin .feed  .input button").html("\u6b63\u5728\u63d0\u4ea4");$(".feedwin .feed  .input button").unbind("click");$.each($(".feedwin .step"),function(){$(this).css("display","none")});$(".feedwin  .feed .step3").css("display","block");$(".feedwin .feed").fadeOut(1E3);$(".feedwin .handle").fadeOut(1100)}function ltrim(a){return a.replace(/^(\s*|\u3000*)/,"")}
function rtrim(a){return a.replace(/(\s*|\u3000*)$/,"")}function trim(a){return ltrim(rtrim(a))}var library=0,result_count=0;
function dosearch(a){if(trim(a.keyword.value.replace(/[\/_]/g," "))=="")return a.keyword.value="",alert("\u5173\u952e\u8bcd\u4e0d\u80fd\u4e3a\u7a7a"),a.keyword.focus(),!1;var b=a.from.value,c=encodeURIComponent(a.keyword.value.replace(/[\/_]/g," "));if(a.socondition&&a.socondition[1].id=="outer"&&a.socondition[1].checked)a="/v?keyword="+c,b>0&&(a+="&from="+b);else{(b=a.searchdomain.value)||(b="http://www.soku.com");var d=a.sbts;a.searchType.value=="bar"&&d!=void 0&&d.value!=""&&(c=c+"_sbt_"+d.value);
a=b+"/search_"+a.searchType.value+"/q_"+c}location.href=a;return!1}function donewsearch(a){if(trim(a.keyword.value.replace(/[\/_]/g," "))=="")return a.keyword.value="",alert("\u5173\u952e\u8bcd\u4e0d\u80fd\u4e3a\u7a7a"),a.keyword.focus(),!1;a="/v?keyword="+encodeURIComponent(a.keyword.value.replace(/[\/_]/g," "));location.href=a;return!1}
function checkTextArea(a){obj=document.getElementById("message");if(obj.value.length>a)return alert("\u60a8\u7684\u8f93\u5165\u5df2\u7ecf\u8d85\u51fa\uff1a"+a+" \u9650\u5236"),!1;return!0}
function search_show(a,b,c){document.getElementById(a+"SearchType").value=b;document.getElementById(a+"Sel").style.display="none";document.getElementById(a+"Slected").innerHTML=c.innerHTML;document.getElementById(a+"q").focus();var c=document.getElementById("soswitch"),d=document.getElementById("sorelated"),e=document.getElementById("searchextend0");if(e!=void 0&&b=="bar"&&a=="head"){e.style.display="block";if(d)d.style.display="none";if(c)c.style.display="none"}else if(e!=void 0&&a=="head"){e.style.display=
"none";if(d)d.style.display="";if(c)c.style.display=""}e=document.getElementById("searchextend1");if(e!=void 0&&(b=="video"||b=="playlist")&&a=="head"){if(e.style.display="block",d)d.style.display="none"}else if(e!=void 0&&a=="head"&&(e.style.display="none",d))d.style.display="";c=document.getElementById("searchextend2");if(e!=void 0&&b=="user"&&a=="head"){if(c.style.display="block",d)d.style.display="none"}else if(e!=void 0&&a=="head"&&(c.style.display="none",d))d.style.display="";try{window.clearTimeout(timer)}catch(f){}return!1}
function csbt(a,b){a.value==b.value?(a.checked=!1,b.value="bar"):b.value=a.value}function drop_mouseover(){try{window.clearTimeout(timer)}catch(a){}}function drop_mouseout(a){$(a+"Sel").style.display=="block"&&(timer=setTimeout("drop_hide('"+a+"')",1E3))}function drop_hide(a){$(a+"Sel").style.display="none"}
function showEpisode(a,b){for(var c=0;c<b;c++)a==c?($("index_"+c).addClassName("current"),$("items"+c).addClassName("current").style.display=""):($("index_"+c).removeClassName("current"),$("items"+c).removeClassName("current").style.display="none")}function clicklog(a,b){if(!a)return!1;var c=new Image;b||(b="");c.src="http://log.so.youku.com/click?log_type=soku_click&type=video&url="+encodeURIComponent(a)+"&keyword="+b+"&source=soku"}var _glogParam={site:1};
function sokuClickStat(a,b){var c=[],d=!1,e;if(a.nodeType){if($(a).attr("_log_type"))c.push("?type="+$(a).attr("_log_type"));else return;$(a).attr("_log_pos")&&c.push("&pos="+$(a).attr("_log_pos"));$(a).attr("_log_ct")&&c.push("&ct="+$(a).attr("_log_ct"));$(a).attr("_log_directpos")&&c.push("&directpos="+$(a).attr("_log_directpos"));$(a).attr("_log_url")&&(e=encodeURIComponent($(a).attr("_log_url")),d=!0)}else{if(a._log_type)c.push("?type="+a._log_type);else return;a._log_pos&&c.push("&pos="+a._log_pos);
a._log_ct&&c.push("&ct="+a._log_ct);a._log_directpos&&c.push("&directpos="+a._log_directpos);a._log_url&&(e=encodeURIComponent(a._log_url),d=!0)}!d&&a.href&&(e=encodeURIComponent(a.href));e&&!e.match(/^javascript(.*)/i)&&c.push("&url="+e);a.keyword?c.push("&keyword="+a.keyword):_glogParam.keyword&&c.push("&keyword="+_glogParam.keyword);_glogParam.site&&c.push("&site="+_glogParam.site);_glogParam.curpage&&c.push("&curpage="+_glogParam.curpage);c.push("&rand"+Math.round(Math.random()*2147483647));c=
"http://lstat.youku.com/sokuClick.php"+c.join("");d=new Image;d.src=c;d.onload=function(){};b&&clicklog(e,_glogParam.keyword)}var winList=null,winVideo=null;
function openVideo(a,b){var c=window.outerWidth||findsize("width"),d=window.outerHeight-165||findsize("height"),e=window.screenLeft||window.screenX||0,f=window.screenTop-100||window.screenY;document.all&&(d+=125);c="left="+((e-8>0?e-8:0)+165)+", top="+f+", location=yes, scrollbars=yes, resizable=yes, toolbar=yes, menubar=yes, directories=yes, status=yes, copyhistory=no, width="+(c-180)+", height="+d;if(winList==null||winList=="undefined")winList=document.createElement("iframe"),winList.id="winList";
if(a)winList.setAttribute("frameborder","no"),winList.setAttribute("border","0"),winList.setAttribute("scrolling","0"),document.body.appendChild(winList),document.body.style.marginLeft="165px",winList.src=a;winVideo=window.open(b,"soVideo",c);winVideo.focus()}
function findsize(a){var b=0,c=0;if(window.innerWidth)b=window.innerWidth;else if(document.body&&document.body.clientWidth)b=document.body.clientWidth;if(window.innerHeight)c=window.innerHeight;else if(document.body&&document.body.clientHeight)c=document.body.clientHeight;if(document.documentElement&&document.documentElement.clientHeight&&document.documentElement.clientWidth)c=document.documentElement.clientHeight,b=document.documentElement.clientWidth;if(a=="width")return b;else if(a=="height")return c}
function focusWin(){document.all||this.blur();try{winVideo.focus()}catch(a){}}String.prototype.GetValue=function(a){a=this.substr(this.indexOf("?")+1).match(RegExp("(^|&)"+a+"=([^&]*)(&|$)"));if(a!=null)return unescape(a[2]);return null};
function sokuHz(){var a=location.href,b=a.GetValue("cp"),a=a.GetValue("cpp");if(null!=b&&b!=""&&"undefined"!=b&&null!=a&&a!=""&&"undefined"!=a)b="http://hz.youku.com/red/redir.php?tp=1&cp="+b+"&cpp="+a,b+="&rand"+Math.round(Math.random()*2147483647),a=new Image,a.src=b,a.onload=function(){}}
function readCookie(a){var b="";a+="=";if(document.cookie.length>0&&(offset=document.cookie.indexOf(a),offset!=-1)){offset+=a.length;end=document.cookie.indexOf(";",offset);if(end==-1)end=document.cookie.length;b=unescape(document.cookie.substring(offset,end))}return b}function writeCookie(a,b,c){var d="";c!=null&&(d=new Date((new Date).getTime()+c*36E5),d="; expires="+d.toGMTString());document.cookie=a+"="+escape(b)+d}
var VideoWall={init:function(a){this.queue=[];this.points={grade1:[{x:740,y:125,w:16,h:10,f:0.2},{x:51,y:304,w:16,h:10,f:0.2},{x:718,y:239,w:16,h:10,f:0.2},{x:50,y:179,w:16,h:10,f:0.2},{x:25,y:522,w:16,h:10,f:0.2},{x:722,y:525,w:16,h:10,f:0.2}],grade2:[{x:557,y:120,w:32,h:20,f:0.4},{x:722,y:196,w:32,h:20,f:0.4},{x:48,y:350,w:32,h:20,f:0.4},{x:500,y:501,w:32,h:20,f:0.4},{x:244,y:508,w:32,h:20,f:0.4},{x:12,y:206,w:32,h:20,f:0.4},{x:122,y:142,w:32,h:20,f:0.4},{x:715,y:136,w:32,h:20,f:0.4},{x:744,y:375,
w:32,h:20,f:0.4},{x:4,y:371,w:25,h:15,f:0.4},{x:389,y:57,w:35,h:21,f:0.4},{x:290,y:16,w:20,h:12,f:0.4},{x:509,y:531,w:32,h:20,f:0.4},{x:16,y:449,w:32,h:20,f:0.4},{x:700,y:285,w:32,h:20,f:0.4},{x:46,y:457,w:32,h:20,f:0.4},{x:430,y:534,w:32,h:20,f:0.4},{x:722,y:511,w:32,h:20,f:0.4},{x:228,y:129,w:32,h:20,f:0.4},{x:72,y:213,w:25,h:15,f:0.4}],grade3:[{x:141,y:498,w:48,h:30,f:0.6},{x:111,y:107,w:48,h:30,f:0.6},{x:202,y:511,w:48,h:30,f:0.6},{x:397,y:500,w:48,h:30,f:0.6},{x:34,y:124,w:48,h:30,f:0.6},{x:701,
y:381,w:48,h:30,f:0.6},{x:446,y:20,w:16,h:10,f:0.6},{x:189,y:525,w:28,h:18,f:0.6},{x:8,y:331,w:48,h:30,f:0.6},{x:33,y:375,w:48,h:30,f:0.6},{x:694,y:201,w:48,h:30,f:0.6},{x:712,y:347,w:48,h:30,f:0.6},{x:340,y:68,w:16,h:10,f:0.6},{x:731,y:284,w:48,h:30,f:0.6},{x:26,y:479,w:48,h:30,f:0.6},{x:422,y:35,w:25,h:16,f:0.6},{x:36,y:310,w:48,h:30,f:0.6},{x:621,y:509,w:48,h:30,f:0.6},{x:295,y:124,w:48,h:30,f:0.6},{x:462,y:125,w:48,h:30,f:0.6},{x:677,y:507,w:48,h:30,f:0.6}],grade4:[{x:63,y:119,w:64,h:40,f:0.8},
{x:156,y:115,w:64,h:40,f:0.8},{x:262,y:512,w:64,h:40,f:0.8},{x:445,y:507,w:64,h:40,f:0.8},{x:386,y:103,w:64,h:40,f:0.8},{x:497,y:109,w:64,h:40,f:0.8},{x:245,y:107,w:64,h:40,f:0.8},{x:540,y:501,w:64,h:40,f:0.8},{x:591,y:110,w:64,h:40,f:0.8},{x:333,y:504,w:64,h:40,f:0.8},{x:17,y:222,w:64,h:40,f:0.8},{x:19,y:161,w:64,h:40,f:0.8},{x:707,y:309,w:64,h:40,f:0.8},{x:654,y:116,w:64,h:40,f:0.8},{x:324,y:48,w:26,h:16,f:0.8},{x:698,y:461,w:64,h:40,f:0.8},{x:710,y:165,w:64,h:40,f:0.8}],grade5:[{x:4,y:258,w:80,
h:50,f:1},{x:52,y:488,w:80,h:50,f:1},{x:604,y:507,w:80,h:50,f:1},{x:331,y:96,w:80,h:50,f:1},{x:697,y:234,w:80,h:50,f:1},{x:308,y:37,w:22,h:13,f:1},{x:5,y:402,w:80,h:50,f:1},{x:695,y:408,w:80,h:50,f:1},{x:116,y:512,w:80,h:50,f:1},{x:355,y:77,w:39,h:24,f:1}]};this.readystate=!1;this.readycount=0;this.dom=$("#wall");this.nodes=[];this.mouselock=!0;if(this.dom.length!=0){var b=this;$.getJSON(a,function(a){if(a.data){for(var a=a.data,d=0,e=a.length;d<e;d++)b.queue.push(a[d]);b.bind()}})}},bind:function(){var a=
this,b=[0],c;for(c in this.points)b.push(this.points[c].length);c=5;for(var d=0,e=this.points.grade5.length,f=0,g=this.queue.length;f<g;f++){f+1>e&&(c--,e+=b[c],d=0);if(!this.points["grade"+c])break;var h=this.points["grade"+c][d];if(!h)break;var i=this.queue[f],j=$('<img src="'+i.pic+'" />').css("opacity",0),k=$('<a onclick="sokuClickStat(this);" href="/v?keyword='+encodeURI(i.name)+'" target="_blank" _log_type="5" _log_pos="2"></a>'),i=$('<span class="name"><span class="text">'+i.name+'</span><span class="bg"></span></span>');
k.append(j).append(i);h=$('<div class="node grade'+c+'"></div>').attr({index:f,w:h.w,h:h.h,f:h.f,X:h.x,Y:h.y,z:c}).css({display:"none",width:0,height:0,top:h.y+h.h/2,left:h.x+h.w/2,zIndex:c}).append(k).appendTo(this.dom);this.bindmouse(h);j.load(function(){a.bubble($(this).parent().parent())});this.nodes.push(h);d++}},bubble:function(a){var b=500+1E3*Math.random(),c=parseInt(a.attr("w")),d=parseInt(a.attr("h")),e=parseInt(a.attr("x")),f=parseInt(a.attr("y")),g=parseFloat(a.attr("f")),h=$(a).find("img"),
i=this;a.css("visibility","visible").animate({width:c,height:d,top:f,left:e},b,"easeInExpo",function(){if(!i.readystate&&(i.readycount++,i.readycount>=i.nodes.length))i.readystate=!0,i.mouselock=!1});h.animate({opacity:g},b,"easeInExpo")},bindmouse:function(a){var b=this;a.mouseenter(function(){if(!b.mouselock){var a=$(this),d=parseInt(a.attr("w")),e=parseInt(a.attr("h")),f=parseInt(a.attr("x")),g=parseInt(a.attr("y"));parseFloat(a.attr("f"));parseInt(a.attr("z"));a.stop().css("zIndex",100).animate({width:128,
height:80,top:g-(80-e-6)/2,left:f-(128-d-6)/2,borderWidth:3},200,"easeInExpo",function(){a.addClass("nodemax")});a.find("img").stop().animate({opacity:1},200,"easeInExpo");return!1}}).mouseleave(function(){if(!b.mouselock){var a=$(this),d=parseInt(a.attr("w")),e=parseInt(a.attr("h")),f=parseInt(a.attr("x")),g=parseInt(a.attr("y")),h=parseFloat(a.attr("f")),i=parseInt(a.attr("z"));a.removeClass("nodemax");a.stop().animate({width:d,height:e,top:g,left:f,borderWidth:0},100,"",function(){a.css("zIndex",
i)});a.find("img").stop().animate({opacity:h},100,"");return!1}})},show:function(){this.dom.fadeIn(300)},hide:function(){this.dom.fadeOut(300)},shake:function(){}};jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(a,b,c,d,e){return jQuery.easing[jQuery.easing.def](a,b,c,d,e)},easeInQuad:function(a,b,c,d,e){return d*(b/=e)*b+c},easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c},easeInOutQuad:function(a,b,c,d,e){if((b/=e/2)<1)return d/2*b*b+c;return-d/2*(--b*(b-2)-1)+c},easeInCubic:function(a,b,c,d,e){return d*(b/=e)*b*b+c},easeOutCubic:function(a,b,c,d,e){return d*((b=b/e-1)*b*b+1)+c},easeInOutCubic:function(a,b,c,d,e){if((b/=e/2)<1)return d/
2*b*b*b+c;return d/2*((b-=2)*b*b+2)+c},easeInQuart:function(a,b,c,d,e){return d*(b/=e)*b*b*b+c},easeOutQuart:function(a,b,c,d,e){return-d*((b=b/e-1)*b*b*b-1)+c},easeInOutQuart:function(a,b,c,d,e){if((b/=e/2)<1)return d/2*b*b*b*b+c;return-d/2*((b-=2)*b*b*b-2)+c},easeInQuint:function(a,b,c,d,e){return d*(b/=e)*b*b*b*b+c},easeOutQuint:function(a,b,c,d,e){return d*((b=b/e-1)*b*b*b*b+1)+c},easeInOutQuint:function(a,b,c,d,e){if((b/=e/2)<1)return d/2*b*b*b*b*b+c;return d/2*((b-=2)*b*b*b*b+2)+c},easeInSine:function(a,
b,c,d,e){return-d*Math.cos(b/e*(Math.PI/2))+d+c},easeOutSine:function(a,b,c,d,e){return d*Math.sin(b/e*(Math.PI/2))+c},easeInOutSine:function(a,b,c,d,e){return-d/2*(Math.cos(Math.PI*b/e)-1)+c},easeInExpo:function(a,b,c,d,e){return b==0?c:d*Math.pow(2,10*(b/e-1))+c},easeOutExpo:function(a,b,c,d,e){return b==e?c+d:d*(-Math.pow(2,-10*b/e)+1)+c},easeInOutExpo:function(a,b,c,d,e){if(b==0)return c;if(b==e)return c+d;if((b/=e/2)<1)return d/2*Math.pow(2,10*(b-1))+c;return d/2*(-Math.pow(2,-10*--b)+2)+c},
easeInCirc:function(a,b,c,d,e){return-d*(Math.sqrt(1-(b/=e)*b)-1)+c},easeOutCirc:function(a,b,c,d,e){return d*Math.sqrt(1-(b=b/e-1)*b)+c},easeInOutCirc:function(a,b,c,d,e){if((b/=e/2)<1)return-d/2*(Math.sqrt(1-b*b)-1)+c;return d/2*(Math.sqrt(1-(b-=2)*b)+1)+c},easeInElastic:function(a,b,c,d,e){var a=1.70158,f=0,g=d;if(b==0)return c;if((b/=e)==1)return c+d;f||(f=e*0.3);g<Math.abs(d)?(g=d,a=f/4):a=f/(2*Math.PI)*Math.asin(d/g);return-(g*Math.pow(2,10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f))+c},easeOutElastic:function(a,
b,c,d,e){var a=1.70158,f=0,g=d;if(b==0)return c;if((b/=e)==1)return c+d;f||(f=e*0.3);g<Math.abs(d)?(g=d,a=f/4):a=f/(2*Math.PI)*Math.asin(d/g);return g*Math.pow(2,-10*b)*Math.sin((b*e-a)*2*Math.PI/f)+d+c},easeInOutElastic:function(a,b,c,d,e){var a=1.70158,f=0,g=d;if(b==0)return c;if((b/=e/2)==2)return c+d;f||(f=e*0.3*1.5);g<Math.abs(d)?(g=d,a=f/4):a=f/(2*Math.PI)*Math.asin(d/g);if(b<1)return-0.5*g*Math.pow(2,10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f)+c;return g*Math.pow(2,-10*(b-=1))*Math.sin((b*e-a)*
2*Math.PI/f)*0.5+d+c},easeInBack:function(a,b,c,d,e,f){f==void 0&&(f=1.70158);return d*(b/=e)*b*((f+1)*b-f)+c},easeOutBack:function(a,b,c,d,e,f){f==void 0&&(f=1.70158);return d*((b=b/e-1)*b*((f+1)*b+f)+1)+c},easeInOutBack:function(a,b,c,d,e,f){f==void 0&&(f=1.70158);if((b/=e/2)<1)return d/2*b*b*(((f*=1.525)+1)*b-f)+c;return d/2*((b-=2)*b*(((f*=1.525)+1)*b+f)+2)+c},easeInBounce:function(a,b,c,d,e){return d-jQuery.easing.easeOutBounce(a,e-b,0,d,e)+c},easeOutBounce:function(a,b,c,d,e){return(b/=e)<1/
2.75?d*7.5625*b*b+c:b<2/2.75?d*(7.5625*(b-=1.5/2.75)*b+0.75)+c:b<2.5/2.75?d*(7.5625*(b-=2.25/2.75)*b+0.9375)+c:d*(7.5625*(b-=2.625/2.75)*b+0.984375)+c},easeInOutBounce:function(a,b,c,d,e){if(b<e/2)return jQuery.easing.easeInBounce(a,b*2,0,d,e)*0.5+c;return jQuery.easing.easeOutBounce(a,b*2-e,0,d,e)*0.5+d*0.5+c}});
(function(a){a.fn.lazyload=function(b){var c={threshold:0,failurelimit:0,event:"scroll",effect:"show",container:window};b&&a.extend(c,b);var d=this;"scroll"==c.event&&a(c.container).bind("scroll",function(){var b=0;d.each(function(){if(!a.abovethetop(this,c)&&!a.leftofbegin(this,c))if(!a.belowthefold(this,c)&&!a.rightoffold(this,c))a(this).trigger("appear");else if(b++>c.failurelimit)return!1});var f=a.grep(d,function(a){return!a.loaded});d=a(f)});this.each(function(){var b=this;void 0==a(b).attr("original")&&
a(b).attr("original",a(b).attr("src"));"scroll"!=c.event||void 0==a(b).attr("src")||c.placeholder==a(b).attr("src")||a.abovethetop(b,c)||a.leftofbegin(b,c)||a.belowthefold(b,c)||a.rightoffold(b,c)?(c.placeholder?a(b).attr("src",c.placeholder):a(b).removeAttr("src"),b.loaded=!1):b.loaded=!0;a(b).one("appear",function(){this.loaded||a("<img />").bind("load",function(){a(b).hide().attr("src",a(b).attr("original"))[c.effect](c.effectspeed);b.loaded=!0}).attr("src",a(b).attr("original"))});"scroll"!=c.event&&
a(b).bind(c.event,function(){b.loaded||a(b).trigger("appear")})});a(c.container).trigger(c.event);return this};a.belowthefold=function(b,c){return(c.container===void 0||c.container===window?a(window).height()+a(window).scrollTop():a(c.container).offset().top+a(c.container).height())<=a(b).offset().top-c.threshold};a.rightoffold=function(b,c){return(c.container===void 0||c.container===window?a(window).width()+a(window).scrollLeft():a(c.container).offset().left+a(c.container).width())<=a(b).offset().left-
c.threshold};a.abovethetop=function(b,c){return(c.container===void 0||c.container===window?a(window).scrollTop():a(c.container).offset().top)>=a(b).offset().top+c.threshold+a(b).height()};a.leftofbegin=function(b,c){return(c.container===void 0||c.container===window?a(window).scrollLeft():a(c.container).offset().left)>=a(b).offset().left+c.threshold+a(b).width()};a.extend(a.expr[":"],{"below-the-fold":"$.belowthefold(a, {threshold : 0, container: window})","above-the-fold":"!$.belowthefold(a, {threshold : 0, container: window})",
"right-of-fold":"$.rightoffold(a, {threshold : 0, container: window})","left-of-fold":"!$.rightoffold(a, {threshold : 0, container: window})"})})(jQuery);
