<ul>
<li><a href="/channel/teleplay____1.html">电视剧榜</a></li>
<li><a href="/channel/movie____1.html">电影榜</a></li>
<!--
<li><a href="/top/rankzy.jsp">综艺榜</a></li>
<li><a href="/top/rankdm.jsp">动漫榜</a></li>

<li><a href="/channel/fun.html">搞笑榜</a></li>
<li><a href="/channel/music.html">音乐榜</a></li>
<li><a href="/channel/sports.html">体育榜</a></li>
<li><a href="/channel/science.html">科教榜</a></li>
<li><a href="/channel/person/1.html">明星榜</a></li>-->
</ul>
