package com.youku.search.console.pojo.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;
import org.apache.torque.map.ColumnMap;
import org.apache.torque.map.InheritanceMap;

/**
 * ?¡§?¡À?¨¹???¨ª??????????
 *
  *  This class was autogenerated by Torque on:
  *
  * [Thu Feb 19 10:34:56 CST 2009]
  *
  */
public class EpisodeLogMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "com.youku.search.console.pojo.map.EpisodeLogMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public synchronized void doBuild() throws TorqueException
    {
    	if ( isBuilt() ) {
    		return;
    	}
        dbMap = Torque.getDatabaseMap("searchteleplay");

        dbMap.addTable("episode_log");
        TableMap tMap = dbMap.getTable("episode_log");
        tMap.setJavaName("EpisodeLog");
        tMap.setOMClass( com.youku.search.console.pojo.EpisodeLog.class );
        tMap.setPeerClass( com.youku.search.console.pojo.EpisodeLogPeer.class );
        tMap.setDescription("?¡§?¡À?¨¹???¨ª??????????");
	    tMap.setPrimaryKeyMethod(TableMap.NATIVE);
        tMap.setPrimaryKeyMethodInfo("episode_log");

        ColumnMap cMap = null;


    // ------------- Column: id --------------------
        cMap = new ColumnMap( "id", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(true);
  		cMap.setNotNull(true);
        cMap.setJavaName( "Id" );
        cMap.setAutoIncrement(true);
  		cMap.setProtected(false);
      		cMap.setDescription("?¡Â?¨¹id??¡Á???");
        		cMap.setInheritance("false");
                cMap.setSize( 11 );
   	              cMap.setPosition(1);
          tMap.addColumn(cMap);
    // ------------- Column: keyword --------------------
        cMap = new ColumnMap( "keyword", tMap);
        cMap.setType( "" );
        cMap.setTorqueType( "VARCHAR" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
  		cMap.setNotNull(true);
        cMap.setJavaName( "Keyword" );
        cMap.setAutoIncrement(false);
  		cMap.setProtected(false);
      		cMap.setDescription("????");
        		cMap.setInheritance("false");
                cMap.setSize( 100 );
   	              cMap.setPosition(2);
          tMap.addColumn(cMap);
    // ------------- Column: fk_episode_id --------------------
        cMap = new ColumnMap( "fk_episode_id", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
  		cMap.setNotNull(true);
        cMap.setJavaName( "FkEpisodeId" );
        cMap.setAutoIncrement(false);
  		cMap.setProtected(false);
      		cMap.setDescription("????ID");
        		cMap.setInheritance("false");
                cMap.setSize( 11 );
   	              cMap.setPosition(3);
          tMap.addColumn(cMap);
    // ------------- Column: createtime --------------------
        cMap = new ColumnMap( "createtime", tMap);
        cMap.setType( "" );
        cMap.setTorqueType( "VARCHAR" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
  		cMap.setNotNull(true);
        cMap.setJavaName( "Createtime" );
        cMap.setAutoIncrement(false);
  		cMap.setProtected(false);
      		cMap.setDescription("???¡§?¡À??");
        		cMap.setInheritance("false");
                cMap.setSize( 100 );
   	              cMap.setPosition(4);
          tMap.addColumn(cMap);
    // ------------- Column: status --------------------
        cMap = new ColumnMap( "status", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
  		cMap.setNotNull(true);
        cMap.setJavaName( "Status" );
        cMap.setAutoIncrement(false);
  		cMap.setProtected(false);
      		cMap.setDescription("¡Á???,0:?????¨ª 1:???? 2???¡§??");
      		cMap.setDefault("0");
      		cMap.setInheritance("false");
                cMap.setSize( 1 );
   	              cMap.setPosition(5);
          tMap.addColumn(cMap);
        tMap.setUseInheritance(false);
    }
}
