package com.youku.soku.manage.admin.copyright.load;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * Ω⁄ƒø≈‰÷√
 *
 * This class was autogenerated by Torque on:
 *
 * [Fri Sep 23 10:46:18 CST 2011]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to CopyrightConf
 */
public abstract class BaseCopyrightConf extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1316745978724L;

    /** The Peer class */
    private static final CopyrightConfPeer peer =
        new CopyrightConfPeer();


    /** The value for the id field */
    private int id;

    /** The value for the name field */
    private String name;

    /** The value for the keyword field */
    private String keyword;

    /** The value for the time field */
    private int time;

    /** The value for the authoritySite field */
    private String authoritySite;

    /** The value for the startTime field */
    private Date startTime;

    /** The value for the endTime field */
    private Date endTime;


    /**
     * Get the Id
     *
     * @return int
     */
    public int getId()
    {
        return id;
    }


    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(int v) 
    {

        if (this.id != v)
        {
            this.id = v;
            setModified(true);
        }


    }

    /**
     * Get the Name
     *
     * @return String
     */
    public String getName()
    {
        return name;
    }


    /**
     * Set the value of Name
     *
     * @param v new value
     */
    public void setName(String v) 
    {

        if (!ObjectUtils.equals(this.name, v))
        {
            this.name = v;
            setModified(true);
        }


    }

    /**
     * Get the Keyword
     *
     * @return String
     */
    public String getKeyword()
    {
        return keyword;
    }


    /**
     * Set the value of Keyword
     *
     * @param v new value
     */
    public void setKeyword(String v) 
    {

        if (!ObjectUtils.equals(this.keyword, v))
        {
            this.keyword = v;
            setModified(true);
        }


    }

    /**
     * Get the Time
     *
     * @return int
     */
    public int getTime()
    {
        return time;
    }


    /**
     * Set the value of Time
     *
     * @param v new value
     */
    public void setTime(int v) 
    {

        if (this.time != v)
        {
            this.time = v;
            setModified(true);
        }


    }

    /**
     * Get the AuthoritySite
     *
     * @return String
     */
    public String getAuthoritySite()
    {
        return authoritySite;
    }


    /**
     * Set the value of AuthoritySite
     *
     * @param v new value
     */
    public void setAuthoritySite(String v) 
    {

        if (!ObjectUtils.equals(this.authoritySite, v))
        {
            this.authoritySite = v;
            setModified(true);
        }


    }

    /**
     * Get the StartTime
     *
     * @return Date
     */
    public Date getStartTime()
    {
        return startTime;
    }


    /**
     * Set the value of StartTime
     *
     * @param v new value
     */
    public void setStartTime(Date v) 
    {

        if (!ObjectUtils.equals(this.startTime, v))
        {
            this.startTime = v;
            setModified(true);
        }


    }

    /**
     * Get the EndTime
     *
     * @return Date
     */
    public Date getEndTime()
    {
        return endTime;
    }


    /**
     * Set the value of EndTime
     *
     * @param v new value
     */
    public void setEndTime(Date v) 
    {

        if (!ObjectUtils.equals(this.endTime, v))
        {
            this.endTime = v;
            setModified(true);
        }


    }

       
        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("Id");
            fieldNames.add("Name");
            fieldNames.add("Keyword");
            fieldNames.add("Time");
            fieldNames.add("AuthoritySite");
            fieldNames.add("StartTime");
            fieldNames.add("EndTime");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Id"))
        {
            return new Integer(getId());
        }
        if (name.equals("Name"))
        {
            return getName();
        }
        if (name.equals("Keyword"))
        {
            return getKeyword();
        }
        if (name.equals("Time"))
        {
            return new Integer(getTime());
        }
        if (name.equals("AuthoritySite"))
        {
            return getAuthoritySite();
        }
        if (name.equals("StartTime"))
        {
            return getStartTime();
        }
        if (name.equals("EndTime"))
        {
            return getEndTime();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Id"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Name"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setName((String) value);
            return true;
        }
        if (name.equals("Keyword"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setKeyword((String) value);
            return true;
        }
        if (name.equals("Time"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setTime(((Integer) value).intValue());
            return true;
        }
        if (name.equals("AuthoritySite"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setAuthoritySite((String) value);
            return true;
        }
        if (name.equals("StartTime"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setStartTime((Date) value);
            return true;
        }
        if (name.equals("EndTime"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEndTime((Date) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(CopyrightConfPeer.ID))
        {
            return new Integer(getId());
        }
        if (name.equals(CopyrightConfPeer.NAME))
        {
            return getName();
        }
        if (name.equals(CopyrightConfPeer.KEYWORD))
        {
            return getKeyword();
        }
        if (name.equals(CopyrightConfPeer.TIME))
        {
            return new Integer(getTime());
        }
        if (name.equals(CopyrightConfPeer.AUTHORITY_SITE))
        {
            return getAuthoritySite();
        }
        if (name.equals(CopyrightConfPeer.START_TIME))
        {
            return getStartTime();
        }
        if (name.equals(CopyrightConfPeer.END_TIME))
        {
            return getEndTime();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (CopyrightConfPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
      if (CopyrightConfPeer.NAME.equals(name))
        {
            return setByName("Name", value);
        }
      if (CopyrightConfPeer.KEYWORD.equals(name))
        {
            return setByName("Keyword", value);
        }
      if (CopyrightConfPeer.TIME.equals(name))
        {
            return setByName("Time", value);
        }
      if (CopyrightConfPeer.AUTHORITY_SITE.equals(name))
        {
            return setByName("AuthoritySite", value);
        }
      if (CopyrightConfPeer.START_TIME.equals(name))
        {
            return setByName("StartTime", value);
        }
      if (CopyrightConfPeer.END_TIME.equals(name))
        {
            return setByName("EndTime", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getId());
        }
        if (pos == 1)
        {
            return getName();
        }
        if (pos == 2)
        {
            return getKeyword();
        }
        if (pos == 3)
        {
            return new Integer(getTime());
        }
        if (pos == 4)
        {
            return getAuthoritySite();
        }
        if (pos == 5)
        {
            return getStartTime();
        }
        if (pos == 6)
        {
            return getEndTime();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("Id", value);
        }
    if (position == 1)
        {
            return setByName("Name", value);
        }
    if (position == 2)
        {
            return setByName("Keyword", value);
        }
    if (position == 3)
        {
            return setByName("Time", value);
        }
    if (position == 4)
        {
            return setByName("AuthoritySite", value);
        }
    if (position == 5)
        {
            return setByName("StartTime", value);
        }
    if (position == 6)
        {
            return setByName("EndTime", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(CopyrightConfPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    CopyrightConfPeer.doInsert((CopyrightConf) this, con);
                    setNew(false);
                }
                else
                {
                    CopyrightConfPeer.doUpdate((CopyrightConf) this, con);
                }
            }

            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
        setId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
        setId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public CopyrightConf copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public CopyrightConf copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public CopyrightConf copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new CopyrightConf(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public CopyrightConf copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new CopyrightConf(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected CopyrightConf copyInto(CopyrightConf copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected CopyrightConf copyInto(CopyrightConf copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected CopyrightConf copyInto(CopyrightConf copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setName(name);
        copyObj.setKeyword(keyword);
        copyObj.setTime(time);
        copyObj.setAuthoritySite(authoritySite);
        copyObj.setStartTime(startTime);
        copyObj.setEndTime(endTime);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected CopyrightConf copyInto(CopyrightConf copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setName(name);
        copyObj.setKeyword(keyword);
        copyObj.setTime(time);
        copyObj.setAuthoritySite(authoritySite);
        copyObj.setStartTime(startTime);
        copyObj.setEndTime(endTime);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public CopyrightConfPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return CopyrightConfPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("CopyrightConf:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("Name = ")
           .append(getName())
           .append("\n");
        str.append("Keyword = ")
           .append(getKeyword())
           .append("\n");
        str.append("Time = ")
           .append(getTime())
           .append("\n");
        str.append("AuthoritySite = ")
           .append(getAuthoritySite())
           .append("\n");
        str.append("StartTime = ")
           .append(getStartTime())
           .append("\n");
        str.append("EndTime = ")
           .append(getEndTime())
           .append("\n");
        return(str.toString());
    }
}
