package com.youku.search.console.pojo;


import org.apache.torque.om.Persistent;

/**
 * ?????ид???????и╣??????
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 18 15:11:50 CST 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class EpisodeVideoUpdateInfo
    extends com.youku.search.console.pojo.BaseEpisodeVideoUpdateInfo
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1290064310953L;

}
