package com.youku.search.console.pojo;


import org.apache.torque.om.Persistent;

/**
 * ????¡Á???¡À¨ª
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jun 11 13:42:54 CST 2009]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class MenuResource
    extends com.youku.search.console.pojo.BaseMenuResource
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1244698974234L;

}
