package com.youku.search.console.pojo;


import org.apache.torque.om.Persistent;

/**
 * ???¡Â????????
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Jun 30 15:16:12 CST 2009]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Trietreerecommend
    extends com.youku.search.console.pojo.BaseTrietreerecommend
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1246346172843L;

}
