package com.youku.search.console.pojo;

/**
 * ¡Á???????????????
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Feb 10 15:25:22 CST 2009]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class VarietyInfoPeer
    extends com.youku.search.console.pojo.BaseVarietyInfoPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1234250722796L;

}
