package com.youku.soku.manage.torque.map;

import java.util.Date;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.ColumnMap;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;

/**
 * Hot Word
 *
  *  This class was autogenerated by Torque on:
  *
  * [Wed Mar 10 16:13:12 CST 2010]
  *
  */
public class HotwordMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "com.youku.soku.manage.torque.map.HotwordMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public synchronized void doBuild() throws TorqueException
    {
        if ( isBuilt() ) {
            return;
        }
        dbMap = Torque.getDatabaseMap("soku");

        dbMap.addTable("hotword");
        TableMap tMap = dbMap.getTable("hotword");
        tMap.setJavaName("Hotword");
        tMap.setOMClass( com.youku.soku.manage.torque.Hotword.class );
        tMap.setPeerClass( com.youku.soku.manage.torque.HotwordPeer.class );
        tMap.setDescription("Hot Word");
        tMap.setPrimaryKeyMethod(TableMap.NATIVE);
        tMap.setPrimaryKeyMethodInfo("hotword");

        ColumnMap cMap = null;


  // ------------- Column: word_id --------------------
        cMap = new ColumnMap( "word_id", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(true);
        cMap.setNotNull(true);
        cMap.setJavaName( "WordId" );
        cMap.setAutoIncrement(true);
        cMap.setProtected(false);
        cMap.setDescription("Hot Word Id");
        cMap.setInheritance("false");
        cMap.setPosition(1);
        tMap.addColumn(cMap);
  // ------------- Column: name --------------------
        cMap = new ColumnMap( "name", tMap);
        cMap.setType( "" );
        cMap.setTorqueType( "VARCHAR" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Name" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Video Name");
        cMap.setInheritance("false");
        cMap.setSize( 100 );
        cMap.setPosition(2);
        tMap.addColumn(cMap);
  // ------------- Column: index_type --------------------
        cMap = new ColumnMap( "index_type", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "IndexType" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Flag to identify whether to show on the index page");
        cMap.setInheritance("false");
        cMap.setPosition(3);
        tMap.addColumn(cMap);
  // ------------- Column: sort --------------------
        cMap = new ColumnMap( "sort", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Sort" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Video Order");
        cMap.setInheritance("false");
        cMap.setPosition(4);
        tMap.addColumn(cMap);
  // ------------- Column: create_date --------------------
        cMap = new ColumnMap( "create_date", tMap);
        cMap.setType( new Date() );
        cMap.setTorqueType( "DATE" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "CreateDate" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Record create date");
        cMap.setInheritance("false");
        cMap.setPosition(5);
        tMap.addColumn(cMap);
  // ------------- Column: modify_date --------------------
        cMap = new ColumnMap( "modify_date", tMap);
        cMap.setType( new Date() );
        cMap.setTorqueType( "DATE" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "ModifyDate" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Record modify date");
        cMap.setInheritance("false");
        cMap.setPosition(6);
        tMap.addColumn(cMap);
  // ------------- Column: trend --------------------
        cMap = new ColumnMap( "trend", tMap);
        cMap.setType( "" );
        cMap.setTorqueType( "VARCHAR" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(false);
        cMap.setJavaName( "Trend" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Trend of the word");
        cMap.setInheritance("false");
        cMap.setSize( 200 );
        cMap.setPosition(7);
        tMap.addColumn(cMap);
  // ------------- Column: item_id --------------------
        cMap = new ColumnMap( "item_id", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "ItemId" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Identify the video belong to which item");
        cMap.setInheritance("false");
        cMap.setPosition(8);
        tMap.addColumn(cMap);
        tMap.setUseInheritance(false);
    }
}
