package com.youku.soku.suggest.orm;


import org.apache.torque.om.Persistent;

/**
 * trieÊ÷Êý¾Ý
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Dec 09 16:56:03 CST 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class TreeWords
    extends com.youku.soku.suggest.orm.BaseTreeWords
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1291884963214L;

}
